In [5]:
a = (1,2,3,4)

In [6]:
type(a)
a

(1, 2, 3, 4)

In [7]:
import numpy as np

In [8]:
new = np.arange(25).reshape(5,5)
red = new[4]
red

array([20, 21, 22, 23, 24])

In [9]:
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
red=new[:,1::2]
red

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [11]:
blue=new[1::2,0:3:2]
blue

array([[ 5,  7],
       [15, 17]])

In [12]:
red[-1,-1]=0

In [13]:
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22,  0, 24]])

In [18]:
a = np.array([2,-3,9,-9,2,45,-34,54])
mask = (a>10)

In [19]:
mask

array([False, False, False, False, False,  True, False,  True], dtype=bool)

In [20]:
b = a[mask]

In [21]:
b

array([45, 54])

In [31]:
a = np.array([3,5,23,4,6,432,2,1,3,32,98])
print(a)
b = a.sort()
a

[  3   5  23   4   6 432   2   1   3  32  98]


array([  1,   2,   3,   3,   4,   5,   6,  23,  32,  98, 432])

In [32]:
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22,  0, 24]])

In [35]:
mask = np.array([new%3==0],dtype=bool)

In [36]:
mask

array([[[ True, False, False,  True, False],
        [False,  True, False, False,  True],
        [False, False,  True, False, False],
        [ True, False, False,  True, False],
        [False,  True, False,  True,  True]]], dtype=bool)

In [40]:
answer = new[mask]

IndexError: too many indices for array

In [42]:
new[new%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21,  0, 24])

In [43]:
np.where(mask,new,np.nan)

array([[[  0.,  nan,  nan,   3.,  nan],
        [ nan,   6.,  nan,  nan,   9.],
        [ nan,  nan,  12.,  nan,  nan],
        [ 15.,  nan,  nan,  18.,  nan],
        [ nan,  21.,  nan,   0.,  24.]]])

In [67]:
output=np.empty_like(new,dtype=float)
output

array([[  7.01413727e-009,   3.74168445e+233,   2.59345444e+161,
          7.97918153e-072,   7.80195971e-013],
       [  1.05894612e-153,   1.72731109e+097,   5.98147503e-154,
          7.01413727e-009,   6.01346953e-154],
       [  3.98220466e+209,   4.83245961e+276,   2.17235265e-153,
          6.94892780e+140,   6.01347002e-154],
       [  6.01347002e-154,   4.44712982e+217,   8.59655122e+030,
          1.16304933e+214,   5.56206154e+180],
       [  6.01347002e-154,   6.01347002e-154,   1.54607730e+262,
          1.56373721e-033,   2.43897339e-154]])

In [71]:
output.fill(np.nan)
output.mean()
output

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])

In [73]:
a.sum?

In [77]:
t = np.array([[1,2,3],[4,5,6]])
t.sum(axis=1)

array([ 6, 15])

In [78]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [79]:
%matplotlib inline

In [89]:
numbers = np.random.randn(5)
index = ['a','b','c','d','e']
my_pd = pd.DataFrame(numbers,index=index)
my_pd

0
a -1.852287
b -0.183091
c  1.131090
d  0.267518
e  0.589447

In [90]:
numbers.data

In [96]:
my_pd.std()

0    1.136048
dtype: float64